# MLIR mutation family configuration

[fitness_criteria]
should_substitute = [
    "ssa_use.ssa_id",
    "non_function_type",
]
no_duplicate = [
]

[parameterization]
blacklist = [
    "generic_operation.string_literal",
]